language: node_js

node_js:
  - '6'
  - '7'

dist: trusty
sudo: required

env:
  global:
  - NODE_ENV=test
  - UDARU_SERVICE_pgdb_password=''

addons:
  postgresql: "9.5"

services:
  - postgresql

before_script:
  - psql -c 'create database "authorization";' -U postgres

script:
  - npm run test:commit-check

after_script:
  - npm run coveralls

jobs:
  include:
    - stage: Publish Docs
      script: ignore
      node_js: "6"
      script:
        - scripts/deploy-gh-pages.sh
